version: '3.8'

services:
  app:
    container_name: app
    image: appscenter/php-nginx-redis:latest
    working_dir: /www/
    volumes:
      - ./:/www
      - redis:/var/lib/redis
    ports:
      - "80:80"
    depends_on:
      - mysql
    restart: on-failure
    tty: true
    stdin_open: true
    networks:
      - network

  mysql:
    image: mysql/mysql-server
    ports:
      - "3307:3306"
    environment:
      - TIME_ZONE="Europe/Moscow"
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=db
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password
    volumes:
      - mysql:/var/lib/mysql
    networks:
      - network
networks:
  network:
    driver: bridge

volumes:
  mysql:
  redis:

